name: Build and deploy

on:
  push:
    branches:
      - master
      - renew_examples

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@master

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit

      - name: Build examples
        run: npm run build

      - name: Deploy to external repository
        uses: pavletto/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY  }}
        with:
          source-directory: dist
          destination-github-username: openglobus
          destination-repository-name: openglobus.github.io
          user-email: github-actions[bot]@users.noreply.github.com
          target-branch: master
          target-directory: examples